### ISSUE TITLE
Long weekday is output as a short one

### ISSUE THREAD

**Issue by halt-hammerzeit** [andyearnshaw/Intl.js#211]
I'm using this library to format date on Node.js and it can't format weekdays and months as "long" in my configuration.

For example, a simple case:

```js
const Intl_polyfill = require('intl')

const date_time_format =
{
	day          : 'numeric',
	month        : 'long'
}

const date_time_formatter = new Intl_polyfill.DateTimeFormat('en', date_time_format)
console.log(date_time_formatter.format(new Date()))
```

Outputs: `Aug 11`

Even though there is the preferred format inside [`en.json`](https://github.com/andyearnshaw/Intl.js/blob/master/locale-data/json/en.json):

```
        "formats": {
            "availableFormats": {
                "MMMd": "MMM d",
                "MMMMd": "MMMM d",
            },
```

It finds the first one and stops?
Or why is it not choosing the right one?

**Comment by caridy** [comment]
That is a good question, I will investigate :)

**Comment by dzonatan** [comment]
Same for me... :| 
Reverting back to `v1.1.0` works as expected (shows `full` date).

**Comment by halt-hammerzeit** [comment]
@dzonatan oh, really? I'll try to revert too then.

**Comment by dzonatan** [comment]
At least for me works. But.. be aware of #154 :| It will spam your browsers console for missing maps.

Hopefully @caridy will take this soon..

**Comment by mmcgahan** [comment]
Just  a bump for this issue with a super-basic example in the Node console (v6.4.0):

```js
> new Intl.DateTimeFormat('en-US', { weekday: 'long' }).format(new Date())
'Tuesday'
> new require('intl').DateTimeFormat('en-US', { weekday: 'long' }).format(new Date())
'Tue'
```

**Comment by caridy** [comment]
@halt-hammerzeit this is now fixed in 1.2.5:

```
$ node
> const Intl_polyfill = require('./')
> const date_time_format =
... {
...     day          : 'numeric',
...     month        : 'long'
... }
> const date_time_formatter = new Intl_polyfill.DateTimeFormat('en', date_time_format)
> console.log(date_time_formatter.format(new Date()))
September 20
```

**Comment by halt-hammerzeit** [comment]
Yeah, it's working now, thanks

**Comment by slifszyc** [comment]
Hey I'm still having this issue:
```
$ node
> const Intl_polyfill = require('./')
> const date_time_format =
... {
...     weekday: 'long'
... }
> const date_time_formatter = new Intl_polyfill.DateTimeFormat('en', date_time_format)
> console.log(date_time_formatter.format(new Date())) // Wednesday
```
but if I add some more formatting options I get `Wed, Oct 11`:
```
$ node
> const Intl_polyfill = require('./')
> const date_time_format =
... {
...     weekday: 'long',
...     month: 'short',
...     day: 'numeric'
... }
> const date_time_formatter = new Intl_polyfill.DateTimeFormat('en', date_time_format)
> console.log(date_time_formatter.format(new Date())) // Wed, Oct 11
```
which is not correct as I set `weekday: 'long'`
